# Generated by Django 5.2.1 on 2025-05-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgnisations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='orgnisations',
            field=models.ManyToManyField(blank=True, null=True, to='orgnisations.organisation'),
        ),
    ]
