# Generated by Django 5.2.1 on 2025-05-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgnisations', '0001_initial'),
        ('users', '0002_alter_users_orgnisations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='orgnisations',
            field=models.ManyToManyField(blank=True, to='orgnisations.organisation'),
        ),
    ]
