# Generated by Django 5.2.2 on 2025-06-13 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgnisations', '0001_initial'),
        ('users', '0005_useraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('is_auth_route', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routers', to='orgnisations.organisation')),
            ],
        ),
    ]
