# Generated by Django 5.2.2 on 2025-06-14 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgnisations', '0001_initial'),
        ('users', '0006_router'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='router',
            name='sort',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='router',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routers', to='orgnisations.organisation'),
        ),
    ]
