# Generated by Django 5.2.2 on 2025-06-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_router_is_global_router_sort_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
