# Generated by Django 5.2.1 on 2025-06-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_router_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_admin',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_staff',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
