version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      # - ./certs:/certs
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_NAME=mydb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
  
  make-migrations:
    build: .
    command: python manage.py makemigrations
    volumes:
      - .:/code
    depends_on:
      - db
    profiles:
      - tasks

  migrate:
    build: .
    command: python manage.py migrate
    volumes:
      - .:/code
    depends_on:
      - db
    profiles:
      - tasks

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5


volumes:
  postgres_data:
