# Generated by Django 5.2.2 on 2025-06-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgnisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
