# Generated by Django 5.2.2 on 2025-06-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='upload_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
